# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 雾非雾的情思
subtitle: 临渊羡鱼，不如退而结网。
description:
author: 雾非雾的情思
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.mspring.org
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# archive
archive_generator:
  per_page: 100

# tag
tag_generator:
  per_page: 100

# category
category_generator: 
  per_page: 100
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
## yilia主题首页：https://github.com/litten/hexo-theme-yilia
## pure主题首页：https://github.com/cofess/hexo-theme-pure
## anatole主题首页：https://github.com/Ben02/hexo-theme-Anatole
## hexo-theme-aomori：https://github.com/lh1me/hexo-theme-aomori
## hexo-theme-icarus：https://github.com/ppoffice/hexo-theme-icarus
theme: pure

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  # repo: git@github.com:gaoyoubo/blog.mspring.org.git
  # 下方的gh_token会被.travis.yml中sed命令替换
  repo: https://GH_TOKEN@github.com/gaoyoubo/blog.mspring.org.git
  branch: master

jsonContent:
  meta: true
  keywords: false # language name option
  dateFormat: undefined # format string
  pages:
    title: true
    slug: true
    date: true
    updated: true
    comments: true
    path: true
    link: true
    permalink: true
    excerpt: true
    keywords: true # but only if root keywords option language was set
    text: true
    raw: false
    content: false
  posts:
    title: true
    slug: true
    date: true
    updated: true
    comments: true
    path: true
    link: true
    permalink: true
    excerpt: true
    keywords: true # but only if root keywords option language was set
    text: true
    raw: false
    content: false
    categories: true
    tags: true

feed:
  type: atom
  path: atom.xml
  limit: 100
  hub:
  content:

neat_enable: true
